language: python
sudo: false
python:
  - 3.8

addons:
  apt:
    packages:
        libfftw3-dev

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nomkl numpy cython setuptools
  - conda install -q -n test-environment $DASK_SPEC || true
  - |
    if [ -z "$SCIPY_WHEELS" ]; then
      conda install -q -n test-environment scipy
      source activate test-environment
    else
      source activate test-environment
      pip install --pre --upgrade --timeout=60 -f "$SCIPY_WHEELS" scipy
    fi
  - pip install cython
  - pip install coverage
  - pip install codecov
  - python setup.py -v build_ext --inplace --define CYTHON_TRACE
  - cython --annotate-coverage coverage.xml --compile-time-env 'HAVE_DOUBLE'=True --compile-time-env 'HAVE_DOUBLE_OMP'=True --compile-time-env 'HAVE_DOUBLE_THREADS'=True --compile-time-env 'HAVE_DOUBLE_MULTITHREADING'=True --compile-time-env 'HAVE_DOUBLE_MPI'=True --compile-time-env 'HAVE_SINGLE'=True --compile-time-env 'HAVE_SINGLE_OMP'=True --compile-time-env 'HAVE_SINGLE_THREADS'=True --compile-time-env 'HAVE_SINGLE_MULTITHREADING'=True --compile-time-env 'HAVE_SINGLE_MPI'=True --compile-time-env 'HAVE_LONG'=True --compile-time-env 'HAVE_LONG_OMP'=True --compile-time-env 'HAVE_LONG_THREADS'=True --compile-time-env 'HAVE_LONG_MULTITHREADING'=True --compile-time-env 'HAVE_LONG_MPI'=True --compile-time-env 'HAVE_MPI'=False pyfftw/pyfftw.pyx
  - cython --annotate-coverage coverage.xml --compile-time-env 'HAVE_DOUBLE'=True --compile-time-env 'HAVE_DOUBLE_OMP'=True --compile-time-env 'HAVE_DOUBLE_THREADS'=True --compile-time-env 'HAVE_DOUBLE_MULTITHREADING'=True --compile-time-env 'HAVE_DOUBLE_MPI'=True --compile-time-env 'HAVE_SINGLE'=True --compile-time-env 'HAVE_SINGLE_OMP'=True --compile-time-env 'HAVE_SINGLE_THREADS'=True --compile-time-env 'HAVE_SINGLE_MULTITHREADING'=True --compile-time-env 'HAVE_SINGLE_MPI'=True --compile-time-env 'HAVE_LONG'=True --compile-time-env 'HAVE_LONG_OMP'=True --compile-time-env 'HAVE_LONG_THREADS'=True --compile-time-env 'HAVE_LONG_MULTITHREADING'=True --compile-time-env 'HAVE_LONG_MPI'=True --compile-time-env 'HAVE_MPI'=False pyfftw/cpu.pxd
  - cython --annotate-coverage coverage.xml --compile-time-env 'HAVE_DOUBLE'=True --compile-time-env 'HAVE_DOUBLE_OMP'=True --compile-time-env 'HAVE_DOUBLE_THREADS'=True --compile-time-env 'HAVE_DOUBLE_MULTITHREADING'=True --compile-time-env 'HAVE_DOUBLE_MPI'=True --compile-time-env 'HAVE_SINGLE'=True --compile-time-env 'HAVE_SINGLE_OMP'=True --compile-time-env 'HAVE_SINGLE_THREADS'=True --compile-time-env 'HAVE_SINGLE_MULTITHREADING'=True --compile-time-env 'HAVE_SINGLE_MPI'=True --compile-time-env 'HAVE_LONG'=True --compile-time-env 'HAVE_LONG_OMP'=True --compile-time-env 'HAVE_LONG_THREADS'=True --compile-time-env 'HAVE_LONG_MULTITHREADING'=True --compile-time-env 'HAVE_LONG_MPI'=True --compile-time-env 'HAVE_MPI'=False pyfftw/config.py
  - cython --annotate-coverage coverage.xml --compile-time-env 'HAVE_DOUBLE'=True --compile-time-env 'HAVE_DOUBLE_OMP'=True --compile-time-env 'HAVE_DOUBLE_THREADS'=True --compile-time-env 'HAVE_DOUBLE_MULTITHREADING'=True --compile-time-env 'HAVE_DOUBLE_MPI'=True --compile-time-env 'HAVE_SINGLE'=True --compile-time-env 'HAVE_SINGLE_OMP'=True --compile-time-env 'HAVE_SINGLE_THREADS'=True --compile-time-env 'HAVE_SINGLE_MULTITHREADING'=True --compile-time-env 'HAVE_SINGLE_MPI'=True --compile-time-env 'HAVE_LONG'=True --compile-time-env 'HAVE_LONG_OMP'=True --compile-time-env 'HAVE_LONG_THREADS'=True --compile-time-env 'HAVE_LONG_MULTITHREADING'=True --compile-time-env 'HAVE_LONG_MPI'=True --compile-time-env 'HAVE_MPI'=False pyfftw/interfaces/numpy_fft.py
  - cython --annotate-coverage coverage.xml --compile-time-env 'HAVE_DOUBLE'=True --compile-time-env 'HAVE_DOUBLE_OMP'=True --compile-time-env 'HAVE_DOUBLE_THREADS'=True --compile-time-env 'HAVE_DOUBLE_MULTITHREADING'=True --compile-time-env 'HAVE_DOUBLE_MPI'=True --compile-time-env 'HAVE_SINGLE'=True --compile-time-env 'HAVE_SINGLE_OMP'=True --compile-time-env 'HAVE_SINGLE_THREADS'=True --compile-time-env 'HAVE_SINGLE_MULTITHREADING'=True --compile-time-env 'HAVE_SINGLE_MPI'=True --compile-time-env 'HAVE_LONG'=True --compile-time-env 'HAVE_LONG_OMP'=True --compile-time-env 'HAVE_LONG_THREADS'=True --compile-time-env 'HAVE_LONG_MULTITHREADING'=True --compile-time-env 'HAVE_LONG_MPI'=True --compile-time-env 'HAVE_MPI'=False pyfftw/interfaces/scipy_fft.py

script:
  - coverage run setup.py test
  - travis/partial.sh
